
/**
 * Represents a collection of symbols/characters categorized by a domain or user preference.
 */
export interface CharacterSet {
  /** A unique identifier for the character set. */
  id: string;
  /** The display name of the character set. */
  name: string;
  /** An array of string characters belonging to this set. */
  characters: string[];
  /** Optional flag indicating if this is a user-created custom set. */
  isCustom?: boolean;
}

/**
 * Structured response from an AI assistant containing character details.
 */
export interface AssistantResponse {
  /** The character symbol being described. */
  character: string;
  /** A textual description of the character's name and meaning. */
  description: string;
  /** An example or explanation of how the character is used in practice. */
  usage: string;
}

/**
 * Metadata associated with a specific symbol, including its description and usage context.
 */
export interface SymbolMetadata {
  /** A textual description of the symbol's name and meaning. */
  description: string;
  /** An example or explanation of how the symbol is used in practice. */
  usage: string;
}

/**
 * Represents an action to modify a custom character palette.
 */
export interface PaletteAction {
  /** The type of modification action to perform on the palette. */
  type: 'CREATE' | 'DELETE' | 'ADD_CHAR' | 'REMOVE_CHAR';
  /** The data payload associated with the action (e.g., character string or palette ID). */
  payload: any;
}

/**
 * A node in a lexical topology, representing a specific domain and its contextual usage of a concept.
 */
export interface TopologyNode {
  /** The specific domain or field of study (e.g., Mathematics, Philosophy). */
  domain: string;
  /** The contextual explanation of how the concept is applied within the domain. */
  context: string;
}

/**
 * Represents a synthesized cross-domain concept linking multiple topology nodes via a latent bridge.
 */
export interface PluriversalKnowledgeCapsule {
  /** The conceptual link or isomorphic relationship discovered between the domains. */
  latent_bridge: string;
  /** An array of domain-specific nodes connected by the latent bridge. */
  nodes: TopologyNode[];
}

/**
 * A multiple-choice question for Study Mode, generated to test symbol knowledge.
 */
export interface QuizQuestion {
  /** The target symbol to be identified. */
  symbol: string;
  /** The correct description or name of the symbol. */
  correctAnswer: string;
  /** An array containing the correct answer and several generated distractors. */
  options: string[];
}

/**
 * Represents the current lifecycle state of the Study Mode feature.
 */
export type StudyModeState = 'idle' | 'loading' | 'active' | 'finished';

// Project Aurelius: Geometric Cognition Types
/**
 * A request payload for exploring geometric cognitive concepts within Project Aurelius.
 */
export interface LatentTopologyRequest {
  /** The foundational concept to be explored or transformed. */
  base_concept: string;
  /** The target geometric framework to apply to the concept. */
  target_geometry: "Hyperbolic" | "Elliptic" | "Spherical" | "Riemannian";
  /** The number of latent or hidden dimensions to simulate. */
  phantom_dimensions: number;
  /** The curvature bias applied to the topological transformation, ranging from -1.0 to 1.0. */
  curvature_bias: number;
}

/**
 * Metrics representing the structural validity and cognitive adherence of an generated concept.
 */
export interface PlausibilityMetric {
  /** The estimated structural similarity index. */
  ssim_estimate: number;
  /** The degree to which the generated concept adheres to physical or defined constraints. */
  physical_adherence: number;
  /** The measure of deviation from the original semantic intent. */
  semantic_drift: number;
}

/**
 * A complete response from the autonomous prompt optimizer in Project Aurelius.
 */
export interface TopologyResponse {
  /** The refined and optimized prompt generated by the oracle. */
  meta_prompt: string;
  /** An array of structural constraints enforced on the prompt. */
  structural_constraints: string[];
  /** The evaluated plausibility metrics for the generated prompt and constraints. */
  plausibility_score: PlausibilityMetric;
  /** A historical record of the optimization steps and adjustments made. */
  provenance_trail: string[];
}

// Agentic Inversion: Plausibility Oracle & Epistemic Escrow Types
/**
 * Represents an interception request by the Epistemic Escrow to resolve ambiguity in user queries.
 */
export interface EpistemicEscrowRequest {
  /** A flag indicating whether the request has been halted due to ambiguity. */
  is_escrowed: boolean;
  /** The calculated Confidence-Fidelity Divergence Index ranging from 0.0 to 1.0. */
  cfd_index: number;
  /** The specific term or concept causing the ambiguity or assumption in the query. */
  ambiguity_source: string;
  /** A proposed question to ask the user to resolve the detected ambiguity. */
  clarifying_question: string;
}

/**
 * Represents the evaluation of a user intent against defined architectural constraints by the Plausibility Oracle.
 */
export interface PlausibilityConstraint {
  /** A flag indicating whether the intent adheres to all evaluated constraints. */
  is_valid: boolean;
  /** The specific constraint that was violated, if any. */
  violated_constraint: string | null;
  /** The reasoning or explanation for why the constraint was violated. */
  justification: string | null;
  /** The recommended action for the user to resolve the constraint violation. */
  required_action: string | null;
}

/**
 * A generalized structure for agentic interventions (Escrow or Oracle Rejection) to interrupt standard flow.
 */
export interface AgenticIntervention {
  /** The type of intervention triggered. */
  type: 'ESCROW' | 'ORACLE_REJECTION';
  /** A user-facing message explaining the intervention. */
  message: string;
  /** The specific details and data associated with the intervention type. */
  details: EpistemicEscrowRequest | PlausibilityConstraint;
}
